# Generated by Django 5.0.1 on 2024-01-04 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(verbose_name='Kategoriya haqida')),
            ],
            options={
                'verbose_name': 'Blog kategoriya',
                'verbose_name_plural': 'Blog kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Maqola nomi')),
                ('description', models.TextField(verbose_name='Maqola haqida')),
                ('short_description', models.TextField(verbose_name='Maqola qisqacha haqida')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Maqola rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory', verbose_name='Maqola kategoriyasi')),
            ],
            options={
                'verbose_name': 'Blog maqola',
                'verbose_name_plural': 'Blog maqolalar',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Fikr')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost', verbose_name='Maqola')),
            ],
            options={
                'verbose_name': 'Blog fikr',
                'verbose_name_plural': 'Blog fikrlar',
            },
        ),
    ]
