# Generated by Django 5.0.1 on 2024-01-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
